baseURL: "https://lanuit.dev"
languageCode: "en"
title: "Steve's website"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Steve Lanuit website"
  description: Resume, blog on programming and stuff
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  
  color:
    textColor:
    secondaryTextColor:
    backgroundColor:
    secondaryBackgroundColor:
    primaryColor: 
    secondaryColor:

    darkmode:
      textColor:
      secondaryTextColor:
      backgroundColor:
      secondaryBackgroundColor:
      primaryColor: "#00897B"
      secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/fav.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Steve Lanuit" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Steve Lanuit"
    subtitle: "I can read and write computer code"
    content: "Passionate about software architecture, software design, graphics programming and agile principles."
    image: /images/avatar.jpg
    bottomImage:
      enable: false
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/files/resume-steve-lanuit.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/slanuit
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/steve-lanuit/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |
      I have been a professional developer for about 19 years and a scrum master for about 4 years.
      
      I worked for 13 years in hospitals and the healthcare industry then I helped set up a startup (1 year as a
      freelancer, complementary activity) to then work in this startup as a lead developer and scrum master.
      Throughout my career, I had the opportunity to build several software from scratch, to make technological
      choices, to advise managers and to support projects in their life cycle.
      
      Passionate about software architecture, software design, graphics programming and agile principles.
      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - src: /images/tech/c-sharp-c.svg
          text: C#
        - src: /images/tech/visual-studio.svg
          text: Visual Studio
        - src: /images/tech/git.svg
          text: Git
        - src: /images/tech/unity-3d.svg
          text: Unity 3D
        - src: /images/tech/react.svg
          text: React
        - src: /images/tech/redux-original.svg
          text: Redux
        - src: /images/tech/azure-devops-color.svg
          text: Azure Devops
        - src: /images/tech/dotnet.svg
          text: .NET
        - src: /images/tech/material-ui.svg
          text: Material UI
        - src: /images/tech/vs-code.svg
          text: VS Code
        - src: /images/tech/javascript-js.svg
          text: Javascript
        - src: /images/tech/typescript-icon.svg
          text: TypesScript
        - src: /images/tech/microsoft-azure.svg
          text: Microsoft Azure
        - src: /images/tech/rabbitmq.svg
          text: RabbitMQ
        - src: /images/tech/file-type-docker.svg
          text: Docker
        - src: /images/tech/kubernetes.svg
          text: Kubernetes
        - src: /images/tech/redis.svg
          text: Redis
        - src: /images/tech/microsoft-sql-server-1.svg
          text: SQL Server
        # - /images/tech/azure-devops-color.svg
        # - /images/tech/unity-3d.svg

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Lead Software Developer and Scrum Master"
        company: "Touch Reality"
        companyUrl: "https://touch-reality.com/"
        date: "Feb 2017 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://touch-reality.com/"
        content: |
          - Recruited dev team members (up to 20 people working in feature teams).
          - Set up the scrum framework, coached teams, managers.
          - Facilitated scrum workshops (daily, sprint planning, sprint review, retrospective).
          - Organized workshops allowing managers to decide together on the product roadmap.
          - Led the technical workshops.
          - Added many features to the Tangible 3D kitchen design tool.
          - Designed a 3D catalog generator to quickly integrate products and materials from kitchen and worktops manufacturers (created a scripting language – CGL).
          - Designed a multi-tenant 3D kitchen planning web tool allowing kitchen shops to integrate a planner into their website.
          - Migrated the entire solution to Azure Cloud.
          - Built various bi-directional connectors to third party systems.
          - Fixed customer issues.
          - Worked 100% remote since 2020.

      - job: "Freelance Software Developer"
        company: "Touch Reality"
        companyUrl: "https://touch-reality.com/"
        date: "Oct 2015 - Feb 2017"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Worked as a freelancer, as a complementary activity, evenings and weekends to design the software allowing the startup Touch Reality to launch on the market.
          - Designed a co-creation tool (customer - seller) on a tangible tabletop allowing a 3D kitchen design experience using physical furniture miniature.
          - Designed sales management software connected to the tangible table (cloud based).

      - job: "IT Project Manager"
        company: "ISoSL"
        companyUrl: "https://www.isosl.be/"
        date: "April 2016 - Feb 2017"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Coordinated the dev team (4 people)
          - Planned, coordinated and monitored various medical and care software projects modules (electronic medical prescription, nursing process…).
          - Planned, coordinated and monitored legal compliance and data connections to healthcare platforms (federal ehealth platform, RSW - Walloon Health Network).
          - Wrote specifications, needs analyses for care services.
          - Actively participated in the development of software solutions.

      - job: "Senior Software Developer"
        company: "ISoSL"
        companyUrl: "https://www.isosl.be/"
        date: "June 2008 - April 2016"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Designed an electronic health record software for the ISoSL psychiatry department (2 hospitals, 51 care units, +1700 users).
          - Designed and integrated the scanning of paper files into the electronic patient file.
          - Designed intuitive patient flow software linked to billing software and care units. Deployed this software in 4 hospitals of the ISoSL group.
          - Developed reports and legal exports of patient data for federal statistics (RPM, DI-RHM).
          - Developed software to centralize scanning of incoming paper mail for administrative services.
          - Developed other internal software for the IT department.
          - Trained new developers.
          - Trained users and trained trainers on the software designed.
          - Fixed customer issues.


      - job: "Software Developer"
        company: "CHP"
        companyUrl: "https://www.isosl.be/"
        date: "April 2004 - June 2008"
        content: |
          - Designed an electronic health record software for the CHP care services (1 hospital, 14 care units).
          - Developed a therapeutic formulary management software for Belgian hospital pharmacies in partnership with the CBIP (Belgian Center for Phamacotherapeutic Information).
          - Continued the software produced during my end-of-study work : a 3D therapeutic serious game helping the cognitive revalidation of patients. (Studies and scientific publications have been carried out by the CHP and the neuropsychology unit of the University of Liège).
          - Fixed customer issues.
          - Trained users.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor, Information Technology"
        school:
          name: "Haute Ecole de la Province de Liège, Rennequin Sualem"
          url: "https://www.hepl.be/"
        date: "2001 - 2004"
        GPA: "highest honors"
        content: |-
          Specialization: industrial computing - digital image processing

          2004 : 
            - Imagine Cup 2004 Competitor
            - Took part in the international software design contest organized by Microsoft – Imagine Cup.
            - Won the first place at the Benelux.
            - Flew to Brazil to participate in the world final (40 countries) and I finished 5th in the world.

      - title: "Certified ScrumMaster® (CSM®)"
        school:
          name: "Scrum Alliance, Inc."
          url: "https://bcert.me/sbucunagb"
        date: "2019"
      - title: "Certified Scrum Product Owner® (CSPO®) "
        school:
          name: "Scrum Alliance, Inc."
          url: "https://bcert.me/stihiixxj"
        date: "2019"
   
  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: s.lanuit@live.be
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/slanuit
      linkedin: https://www.linkedin.com/in/steve-lanuit/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"